permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: metro
  email: codegeeke@outlook.com
  link: http://codingmanjs.github.io/index.html
  github: http://github.com/codingmanjs

# 站点信息
title: Metro的博客
description: Metro的博客
url: http://codingmanjs.github.io/index.html
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://d.pcs.baidu.com/thumbnail/0a534c88ebfcf4716855b0e3c38476a5?fid=2620303470-250528-832269482564476&time=1448935200&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-SAa0l6lwc1%2FwvsiG%2BkzM6VsLWcs%3D&rt=sh&expires=2h&r=608307921&sharesign=unknown&size=c710_u500&quality=100
favicon: http://d.pcs.baidu.com/thumbnail/0a534c88ebfcf4716855b0e3c38476a5?fid=2620303470-250528-832269482564476&time=1448935200&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-SAa0l6lwc1%2FwvsiG%2BkzM6VsLWcs%3D&rt=sh&expires=2h&r=608307921&sharesign=unknown&size=c710_u500&quality=100

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# # disqus 设置
# disqus:
#   shortname: suyan-zh
